# Generated by Django 5.1.1 on 2024-09-30 20:37

import core.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Updating')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('game', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=1500, verbose_name='Descrição')),
                ('genero', models.CharField(max_length=100, verbose_name='Genero')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Rating')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('desenvolvedor', models.CharField(max_length=100, verbose_name='Desenvolvedor')),
                ('distribuidor', models.CharField(max_length=100, verbose_name='Distribuído')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 347, 'width': 560}}, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Updating')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('membro', models.CharField(max_length=100, verbose_name='Membro')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
                ('nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 200, 'width': 200}}, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
            },
        ),
    ]
