# Generated by Django 5.1.1 on 2024-09-18 00:44

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Updating')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('game', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=300, verbose_name='Descrição')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='games', variations={'thumb': {'crop': True, 'height': 347, 'width': 560}}, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
    ]
