# Generated by Django 5.1.1 on 2024-10-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='genero',
            new_name='gender',
        ),
    ]
