# Generated by Django 5.1.1 on 2024-10-04 00:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Updating')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nota')),
                ('favorito', models.BooleanField(default=False, verbose_name='Favorito?')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.games')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.membro')),
            ],
            options={
                'verbose_name': 'Avaliação de Jogo',
                'verbose_name_plural': 'Avaliações de Jogos',
                'unique_together': {('membro', 'game')},
            },
        ),
    ]
