# Generated by Django 5.1.1 on 2024-09-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_games_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='ano',
            field=models.IntegerField(default=None, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='games',
            name='desenvolvedor',
            field=models.CharField(default=None, max_length=100, verbose_name='Desenvolvedor'),
        ),
        migrations.AddField(
            model_name='games',
            name='distribuidor',
            field=models.CharField(default=None, max_length=100, verbose_name='Distribuído'),
        ),
        migrations.AddField(
            model_name='games',
            name='genero',
            field=models.CharField(default=None, max_length=100, verbose_name='Genero'),
        ),
    ]
