# Generated by Django 5.1.1 on 2024-10-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_genero_games_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='gender',
            new_name='genero',
        ),
    ]
