# Generated by Django 5.1.1 on 2024-10-04 00:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gamerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerating',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='games',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Rating'),
        ),
    ]
