# Generated by Django 5.1.1 on 2024-10-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_gender_games_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video'),
        ),
    ]
