# Generated by Django 5.1.1 on 2024-09-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_games_ano_games_desenvolvedor_games_distribuidor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='ano',
            field=models.IntegerField(default=None),
        ),
    ]
