# Generated by Django 5.1.1 on 2024-09-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_games_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='ano',
            field=models.IntegerField(default=1980),
        ),
    ]
