# Generated by Django 5.1.1 on 2024-10-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_games_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='genero',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Puzzle', 'Puzzle'), ('Racing', 'Racing'), ('RPG', 'RPG'), ('Shooter', 'Shooter'), ('Simulation', 'Simulation'), ('Sports', 'Sports'), ('Strategy', 'Strategy')], max_length=100, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='games',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Video'),
        ),
    ]
