# Generated by Django 5.1.1 on 2024-10-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_games_genero_alter_games_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
    ]
