# Generated by Django 5.1.1 on 2024-09-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_games_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
