# Generated by Django 5.1.1 on 2024-10-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0007_genero_remove_games_genero_games_generos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='criado',
        ),
        migrations.AddField(
            model_name='membro',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Os grupos aos quais o usuário pertence.', related_name='membro_set', to='auth.group', verbose_name='grupos'),
        ),
        migrations.AddField(
            model_name='membro',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membro',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='membro',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='membro',
            name='password',
            field=models.CharField(default='curio5813#$', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membro',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='As permissões específicas para este usuário.', related_name='membro_permissions_set', to='auth.permission', verbose_name='permissões do usuário'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='membro',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='membro',
            name='senha',
            field=models.CharField(default='curio5813#$', max_length=100, verbose_name='Senha'),
        ),
    ]
