# Generated by Django 5.1.1 on 2024-09-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_games_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='ano',
        ),
    ]
