# Generated by Django 5.1.1 on 2024-09-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_games_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='ano',
            field=models.IntegerField(default=1980, verbose_name='Ano'),
            preserve_default=False,
        ),
    ]
