# Generated by Django 5.1.1 on 2024-10-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_membro_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
