# Generated by Django 5.1.1 on 2024-10-10 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_membro_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='senha',
        ),
    ]
