# Generated by Django 5.1.1 on 2024-09-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_games_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='desenvolvedor',
            field=models.CharField(max_length=100, verbose_name='Desenvolvedor'),
        ),
        migrations.AlterField(
            model_name='games',
            name='distribuidor',
            field=models.CharField(max_length=100, verbose_name='Distribuído'),
        ),
        migrations.AlterField(
            model_name='games',
            name='genero',
            field=models.CharField(max_length=100, verbose_name='Genero'),
        ),
    ]
