# Generated by Django 5.1.1 on 2024-09-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_games_desenvolvedor_alter_games_distribuidor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=9.3, max_digits=2, verbose_name='Rating'),
            preserve_default=False,
        ),
    ]
