# Generated by Django 5.1.1 on 2024-10-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_membro_is_admin_remove_membro_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
