# Generated by Django 5.1.1 on 2024-09-18 23:32

import core.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_games_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Updating')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuário ')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
                ('nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 200, 'width': 200}}, verbose_name='Imagem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
