# Generated by Django 5.1.1 on 2024-10-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_membro_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
