# Generated by Django 5.1.1 on 2024-09-18 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_membro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membro',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
