# Generated by Django 5.1.1 on 2024-09-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_membro_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membro',
            options={'verbose_name': 'Membro', 'verbose_name_plural': 'Membros'},
        ),
        migrations.RemoveField(
            model_name='membro',
            name='usuario',
        ),
        migrations.AddField(
            model_name='membro',
            name='membro',
            field=models.CharField(default=19772010, max_length=100, verbose_name='Membro'),
            preserve_default=False,
        ),
    ]
