# Generated by Django 5.1.1 on 2024-10-10 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_membro_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='is_admin',
        ),
    ]
