# Generated by Django 5.1.1 on 2024-10-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_membro_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membro',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
