# Generated by Django 5.1.1 on 2024-10-16 17:26

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_blogpost_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='static/img/games', variations={'thumbnail': (700, 400, True)}),
        ),
    ]
