# Generated by Django 5.1.1 on 2024-10-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_blogpost_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='conclusion',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Conclusion'),
        ),
        migrations.AddField(
            model_name='games',
            name='gameplay',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Gameplay'),
        ),
        migrations.AddField(
            model_name='games',
            name='graphics',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Graphics'),
        ),
        migrations.AddField(
            model_name='games',
            name='sound_and_music',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Sound and Music'),
        ),
    ]
