# Generated by Django 5.1.1 on 2024-11-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_games_conclusion_games_gameplay_games_graphics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Bio'),
        ),
    ]
