# Generated by Django 5.1.1 on 2024-11-18 17:03

import core.models
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_membro_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='capa',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 450, 'width': 300}}, verbose_name='Capa'),
        ),
    ]
