# Generated by Django 5.1.1 on 2024-11-18 17:21

import core.models
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_games_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='capa',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 723, 'width': 500}}, verbose_name='Capa'),
        ),
    ]
