# Generated by Django 5.1.1 on 2024-11-25 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_games_capa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Campeonato')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('start_date', models.DateTimeField(verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(verbose_name='Data de Término')),
                ('max_participants', models.PositiveIntegerField(default=16, verbose_name='Máximo de Participantes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.games', verbose_name='Jogo')),
                ('participants', models.ManyToManyField(blank=True, related_name='tournaments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
