# Generated by Django 5.1.1 on 2024-11-25 17:43

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_tournament'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'Campeonato', 'verbose_name_plural': 'Campeonatos'},
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='participants',
        ),
        migrations.AddField(
            model_name='tournament',
            name='capa',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='tournaments/capas', variations={'thumb': {'crop': True, 'height': 723, 'width': 500}}, verbose_name='Capa do Campeonato'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_participants',
            field=models.IntegerField(default=16, verbose_name='Máximo de Participantes'),
        ),
    ]
