# Generated by Django 5.1.1 on 2024-11-25 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_tournament_capa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['start_date'], 'verbose_name': 'Campeonato', 'verbose_name_plural': 'Campeonatos'},
        ),
        migrations.AddField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/capas/', verbose_name='Capa do Campeonato'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_participants',
            field=models.IntegerField(default=16, help_text='Número máximo de participantes permitidos.', verbose_name='Máximo de Participantes'),
        ),
    ]
