# Generated by Django 5.1.1 on 2025-02-01 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_tournament_options_tournament_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Rating'),
        ),
    ]
