# Generated by Django 5.1.1 on 2025-02-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_games_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='membro',
            field=models.CharField(max_length=16, verbose_name='Membro'),
        ),
    ]
