# Generated by Django 5.1.6 on 2025-02-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_membro_membro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='games/images/', verbose_name='Imagem'),
        ),
    ]
