# Generated by Django 5.1.6 on 2025-02-14 12:53

import core.models
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_games_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 347, 'width': 560}}, verbose_name='Imagem'),
        ),
    ]
