# Generated by Django 5.1.6 on 2025-02-15 15:52

import core.models
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_games_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='capa',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, storage='storages.backends.s3boto3.S3Boto3Storage', upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 723, 'width': 500}}, verbose_name='Capa'),
        ),
        migrations.AlterField(
            model_name='games',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, storage='storages.backends.s3boto3.S3Boto3Storage', upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 347, 'width': 560}}, verbose_name='Imagem'),
        ),
    ]
