# Generated by Django 5.1.6 on 2025-02-27 00:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0040_alter_games_capa_alter_games_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={},
        ),
        migrations.AlterModelOptions(
            name='membro',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='imagem',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='blog'),
        ),
        migrations.AlterField(
            model_name='games',
            name='capa',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='games_covers'),
        ),
        migrations.AlterField(
            model_name='games',
            name='imagem',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='games'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='members'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='capa',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='tournament_covers'),
        ),
    ]
