# Generated by Django 5.1.6 on 2025-02-15 17:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_games_capa_alter_games_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='imagem',
            field=models.ImageField(upload_to='img/blog', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='games',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_file_path, verbose_name='Capa'),
        ),
        migrations.AlterField(
            model_name='games',
            name='imagem',
            field=models.ImageField(upload_to=core.models.get_file_path, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_file_path, verbose_name='Imagem'),
        ),
    ]
