# Generated by Django 5.1.6 on 2025-04-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_genero_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='nome',
            field=models.CharField(choices=[('ADVENTURE', 'Adventure'), ('RTS', 'Real-Time Strategy'), ('TBS', 'Turn-Based Strategy / Tactics'), ('RPG', 'Role-Playing Game'), ('FPS', 'First-Person Shooter'), ('SIMULATION', 'Simulation'), ('PLATFORMER', 'Platformer'), ('RACING', 'Racing'), ('WAR_SIM', 'War Simulation / Military Strategy'), ('SURVIVAL_HORROR', 'Survival Horror'), ('MMORPG', 'Massively Multiplayer Online RPG'), ('SPORT', 'Sport')], max_length=100, unique=True, verbose_name='Nome'),
        ),
    ]
