# Generated by Django 5.1.6 on 2025-02-15 18:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_blogpost_imagem_alter_games_capa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='imagem',
            field=models.ImageField(storage='storages.backends.s3boto3.S3Boto3Storage', upload_to='img/blog', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='games',
            name='capa',
            field=models.ImageField(blank=True, null=True, storage='storages.backends.s3boto3.S3Boto3Storage', upload_to=core.models.get_file_path, verbose_name='Capa'),
        ),
        migrations.AlterField(
            model_name='games',
            name='imagem',
            field=models.ImageField(storage='storages.backends.s3boto3.S3Boto3Storage', upload_to=core.models.get_file_path, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, storage='storages.backends.s3boto3.S3Boto3Storage', upload_to=core.models.get_file_path, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='capa',
            field=models.ImageField(blank=True, null=True, storage='storages.backends.s3boto3.S3Boto3Storage', upload_to='tournaments/capas/', verbose_name='Capa do Campeonato'),
        ),
    ]
