# Generated by Django 5.1.6 on 2025-04-17 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_genero_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amizade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceita', models.BooleanField(default=False)),
                ('solicitada_em', models.DateTimeField(auto_now_add=True)),
                ('de_membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amizades_enviadas', to=settings.AUTH_USER_MODEL)),
                ('para_membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amizades_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('de_membro', 'para_membro')},
            },
        ),
    ]
