# Generated by Django 5.1.6 on 2025-04-22 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_genero_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='jogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.games', verbose_name='Jogo relacionado'),
        ),
    ]
