# Generated by Django 5.1.6 on 2025-04-22 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_blogpost_jogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='jogo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.games', verbose_name='Jogo relacionado'),
            preserve_default=False,
        ),
    ]
