# Generated by Django 5.1.6 on 2025-04-25 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_gamecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.gamecomment'),
        ),
    ]
