# Generated by Django 5.1.6 on 2025-04-27 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='de_membro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_enviadas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='comentario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.gamecomment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('favorito', 'Favorito'), ('resposta', 'Resposta')], max_length=20),
        ),
    ]
