# Generated by Django 5.1.6 on 2025-04-29 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_notificacao_de_membro_alter_notificacao_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comentarios_curtidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Notificacao',
        ),
    ]
