# Generated by Django 5.1.6 on 2025-04-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_notificacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacao',
            old_name='lida',
            new_name='visualizada',
        ),
    ]
