# Generated by Django 5.1.6 on 2025-05-12 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_mensagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_min', models.CharField(blank=True, max_length=200, null=True, verbose_name='SO Mínimo')),
                ('cpu_min', models.CharField(blank=True, max_length=200, null=True, verbose_name='CPU Mínima')),
                ('ram_min', models.CharField(blank=True, max_length=100, null=True, verbose_name='RAM Mínima')),
                ('gpu_min', models.CharField(blank=True, max_length=200, null=True, verbose_name='GPU Mínima')),
                ('armazenamento_min', models.CharField(blank=True, max_length=100, null=True, verbose_name='Armazenamento Mínimo')),
                ('so_rec', models.CharField(blank=True, max_length=200, null=True, verbose_name='SO Recomendado')),
                ('cpu_rec', models.CharField(blank=True, max_length=200, null=True, verbose_name='CPU Recomendada')),
                ('ram_rec', models.CharField(blank=True, max_length=100, null=True, verbose_name='RAM Recomendada')),
                ('gpu_rec', models.CharField(blank=True, max_length=200, null=True, verbose_name='GPU Recomendada')),
                ('armazenamento_rec', models.CharField(blank=True, max_length=100, null=True, verbose_name='Armazenamento Recomendado')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='core.games')),
            ],
            options={
                'verbose_name': 'Requisito de Sistema',
                'verbose_name_plural': 'Requisitos de Sistema',
            },
        ),
    ]
