# Generated by Django 5.1.6 on 2025-05-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_systemrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemrequirement',
            name='audio_min',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Áudio Mínimo'),
        ),
        migrations.AddField(
            model_name='systemrequirement',
            name='audio_rec',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Áudio Recomendado'),
        ),
    ]
