# Generated by Django 5.1.6 on 2025-05-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_systemrequirement_audio_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='tempo_all_styles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='All Styles (h)'),
        ),
        migrations.AddField(
            model_name='games',
            name='tempo_completionist',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Completionist (h)'),
        ),
        migrations.AddField(
            model_name='games',
            name='tempo_main_extras',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Main + Extras (h)'),
        ),
        migrations.AddField(
            model_name='games',
            name='tempo_main_story',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Main Story (h)'),
        ),
    ]
