# Generated by Django 5.1.6 on 2025-05-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_games_tempo_all_styles_games_tempo_completionist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='gog_affiliate_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link GOG (afiliado)'),
        ),
    ]
