# Generated by Django 5.1.6 on 2025-05-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_games_gog_affiliate_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='nome',
            field=models.CharField(choices=[('ADVENTURE', 'Adventure'), ('RTS', 'Real-Time Strategy'), ('TBS', 'Turn-Based Strategy / Tactics'), ('RPG', 'Role-Playing Game'), ('FPS', 'First-Person Shooter'), ('Simulation', 'Simulation'), ('Platformer', 'Platformer'), ('Racing', 'Racing'), ('War Sim', 'War Simulation / Military Strategy'), ('Survival Horror', 'Survival Horror'), ('MMORPG', 'Massively Multiplayer Online RPG'), ('Sports', 'Sports'), ('Point-and-Click', 'Point-and-Click'), ('Puzzle', 'Puzzle')], max_length=100, unique=True, verbose_name='Nome'),
        ),
    ]
