# Generated by Django 5.1.6 on 2026-06-22 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_alter_games_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="games",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="core/static/games_videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mkv", "webm"]
                    )
                ],
                verbose_name="Vídeo Local",
            ),
        ),
    ]
