# Generated by Django 5.1.6 on 2026-06-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_alter_games_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genero",
            name="nome",
            field=models.CharField(
                choices=[
                    ("Adventure", "Adventure"),
                    ("Action", "Action"),
                    ("Noir", "Noir"),
                    ("Crime", "Crime"),
                    ("RTS", "Real-Time Strategy"),
                    ("TBS", "Turn-Based Strategy / Tactics"),
                    ("RPG", "Role-Playing Game"),
                    ("TPS", "Third-Person Shooter"),
                    ("FPS", "First-Person Shooter"),
                    ("Simulation", "Simulation"),
                    ("Platformer", "Platformer"),
                    ("Racing", "Racing"),
                    ("War Sim", "War Simulation / Military Strategy"),
                    ("Survival Horror", "Survival Horror"),
                    ("MMORPG", "Massively Multiplayer Online RPG"),
                    ("Sport", "Sport"),
                    ("Point-and-Click", "Point-and-Click"),
                    ("Puzzle", "Puzzle"),
                    ("Sci-Fi", "Sci-Fi"),
                    ("Fantasy", "Fantasy"),
                ],
                max_length=100,
                unique=True,
                verbose_name="Nome",
            ),
        ),
    ]
