# Generated by Django 5.1.6 on 2026-07-31 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_alter_games_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
    ]
