# Generated by Django 5.1.1 on 2024-09-22 22:59

import stdimage.models
import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customusuarios_usable_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusuarios',
            name='imagem',
            field=stdimage.models.StdImageField(default='static/img/authors/1_1.jpg', force_min_size=False, upload_to=usuarios.models.get_file_path, variations={'thumb': {'crop': True, 'height': 200, 'width': 200}}, verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='customusuarios',
            name='nascimento',
            field=models.DateField(default='1980-01-01', verbose_name='Data de Nascimento'),
        ),
    ]
