# Generated by Django 5.1.1 on 2024-09-23 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_customusuarios_imagem_customusuarios_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusuarios',
            name='imagem',
        ),
    ]
